CREATE TABLE IF NOT EXISTS TB_PATIENT (
    id UUID PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    gender CHARACTER(1) NOT NULL,
    cpf VARCHAR(20) UNIQUE NOT NULL,
    rg VARCHAR(20) UNIQUE NOT NULL,
    age INT NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    birth_date DATE NOT NULL,
    register_date DATE NOT NULL
);