ALTER TABLE TB_PATIENT ALTER COLUMN cpf SET DATA TYPE VARCHAR(11);
ALTER TABLE TB_PATIENT ALTER COLUMN rg SET DATA TYPE VARCHAR(9);
ALTER TABLE TB_PATIENT ALTER COLUMN phone_number SET DATA TYPE VARCHAR(11);
